site_name: Chia-Tea ğŸŒ¿ğŸµ
site_url: https://Tea-n-Tech.github.io/chia-tea/

theme:
  name: material

nav:
  - Home: index.md
  - Quick-Start: quick_start.md
  - Architecture Guide: architecture_summary.md
  - FAQ: faq.md
